// File generated by FlutterFire CLI from google-services.json.
// DO NOT EDIT MANUALLY. Re-run FlutterFire CLI if your config changes.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the current platform.
///
/// Usage:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Web is not configured: fall back to Android options.
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return android; // re-use android options as fallback
      case TargetPlatform.windows:
        return android; // re-use android options as fallback
      case TargetPlatform.linux:
        return android; // re-use android options as fallback
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFjgho6dKCLTGR8kw2u3KDfsENO5Nrbiw',
    appId: '1:343070737416:android:25d91e888aa7123a18fdbd',
    messagingSenderId: '343070737416',
    projectId: 'nestify-a7fb5',
    storageBucket: 'nestify-a7fb5.firebasestorage.app',
  );

  // iOS config — update these with your actual GoogleService-Info.plist values
  // if you have an iOS build. For now mirrors Android values.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFjgho6dKCLTGR8kw2u3KDfsENO5Nrbiw',
    appId: '1:343070737416:ios:25d91e888aa7123a18fdbd',
    messagingSenderId: '343070737416',
    projectId: 'nestify-a7fb5',
    storageBucket: 'nestify-a7fb5.firebasestorage.app',
    iosClientId: '',
    iosBundleId: 'com.nestify.nestify',
  );
}
